name: carotv
description: A TV application from ClassicTech.
publish_to: none

version: 1.0.0+1
# Major [Drastic]. Patch[Add/removal]. [minor-changes] + [Build Number]

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  permission_handler: ^11.0.1
  upgrader: ^9.0.0
  equatable: ^2.0.5
  lottie: ^2.7.0
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^2.3.8
  dartz: ^0.10.1
  get_it: ^7.6.7
  go_router: ^13.1.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/

fonts:
  - family: PoppinsRegular
    fonts:
      - asset: assets/fonts/Poppins/Poppins-Regular.ttf
  - family: PoppinsLight
    fonts:
      - asset: assets/fonts/Poppins/Poppins-Light.ttf
  - family: PoppinsMedium
    fonts:
      - asset: assets/fonts/Poppins/Poppins-Medium.ttf
  - family: PoppinsBold
    fonts:
      - asset: assets/fonts/Poppins/Poppins-Bold.ttf